version: "3.8"

services:
  web:
    container_name: web
    hostname: web
    networks:
      - web-network
    build:
      context: ./app
    restart: always
    #    ports:
    #      - "127.0.0.1:3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://gateway:80
      - NEXT_PUBLIC_NODE_ENV=production
      - NEXT_PUBLIC_YANDEX_API_KEY=my_yandex_api_key
      - NEXT_PUBLIC_CRYPTO_SECRET_KEY=my_crypto_secret_key
      - NEXT_PUBLIC_DOMAIN_GET_LOCATION=my_get_location_url
      - S3_BUCKET_PUBLIC_DOMAIN=my_s3_url
    volumes:
      - /app
      - /app/node_modules
  #      - web-static:/app/.next/static

  nginx_web:
    container_name: nginx_web
    image: nginx:1.19.3
    networks:
      - web-network
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always

networks:
  web-network:
    external: true
#volumes:
#  web-static:
