version: "3.8"

services:
  web:
    container_name: web
    hostname: web
    networks:
      - web-network
    build:
      context: ./app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:9000
      - NEXT_PUBLIC_NODE_ENV=production
      - NEXT_PUBLIC_YANDEX_API_KEY=5a50ba23-ce9a-45cd-be41-849e6f0c3f1e
      - NEXT_PUBLIC_CRYPTO_SECRET_KEY=Z+sE4e41PixbihRODVgCV5r7T+si1C7PteX3t1FPPfM=
    volumes:
      - /app
      - /app/node_modules
  #      - web-static:/app/.next/static

  nginx_web:
    container_name: nginx_web
    image: nginx:1.19.3
    networks:
      - web-network
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

networks:
  web-network:
    external: true
#volumes:
#  web-static:
