export enum EProfileEditFormFields {
  DisplayName = "displayName",
  Birthday = "birthday",
  Gender = "gender",
  SearchGender = "searchGender",
  Location = "location",
  Description = "description",
  Image = "image",
  TelegramUserID = "telegramUserId",
  TelegramUsername = "telegramUsername",
  TelegramFirstName = "telegramFirstName",
  TelegramLastName = "telegramLastName",
  TelegramLanguageCode = "telegramLanguageCode",
  TelegramAllowsWriteToPm = "telegramAllowsWriteToPm",
  TelegramQueryId = "telegramQueryId",
  TelegramInitDataCrypt = "telegramInitDataCrypt",
  Latitude = "latitude",
  Longitude = "longitude",
  AgeFrom = "ageFrom",
  AgeTo = "ageTo",
  Distance = "distance",
  Page = "page",
  Size = "size",
  Csrf = "csrf",
  IsImages = "isImages",
}
