import { enUS, ru } from "date-fns/locale";
import { ELanguage } from "@/app/shared/enums";

const languageOptionsRu = [
  { label: "русский", value: ELanguage.Ru },
  { label: "английский", value: ELanguage.En },
  { label: "арабский", value: ELanguage.Ar },
  { label: "белорусский", value: ELanguage.Be },
  { label: "каталанский", value: ELanguage.Ca },
  { label: "чешский", value: ELanguage.Cs },
  { label: "немецкий", value: ELanguage.De },
  { label: "испанский", value: ELanguage.Es },
  { label: "финский", value: ELanguage.Fi },
  { label: "французский", value: ELanguage.Fr },
  { label: "иврит", value: ELanguage.He },
  { label: "хорватский", value: ELanguage.Hr },
  { label: "венгерский", value: ELanguage.Hu },
  { label: "индонезийский", value: ELanguage.Id },
  { label: "итальянский", value: ELanguage.It },
  { label: "японский", value: ELanguage.Ja },
  { label: "казахский", value: ELanguage.Kk },
  { label: "корейский", value: ELanguage.Ko },
  { label: "нидерландский", value: ELanguage.Nl },
  { label: "норвежский", value: ELanguage.No },
  { label: "португальский", value: ELanguage.Pt },
  { label: "шведский", value: ELanguage.Sv },
  { label: "украинский", value: ELanguage.Uk },
  { label: "китайский", value: ELanguage.Zh },
];

const languageOptionsEn = [
  { label: "russian", value: ELanguage.Ru },
  { label: "english", value: ELanguage.En },
  { label: "arab", value: ELanguage.Ar },
  { label: "belorussian", value: ELanguage.Be },
  { label: "catalan", value: ELanguage.Ca },
  { label: "czech", value: ELanguage.Cs },
  { label: "german", value: ELanguage.De },
  { label: "spanish", value: ELanguage.Es },
  { label: "finnish", value: ELanguage.Fi },
  { label: "french", value: ELanguage.Fr },
  { label: "hebrew", value: ELanguage.He },
  { label: "croatian", value: ELanguage.Hr },
  { label: "hungarian", value: ELanguage.Hu },
  { label: "indonesian", value: ELanguage.Id },
  { label: "italian", value: ELanguage.It },
  { label: "japanese", value: ELanguage.Ja },
  { label: "kazakh", value: ELanguage.Kk },
  { label: "korean", value: ELanguage.Ko },
  { label: "dutch", value: ELanguage.Nl },
  { label: "norwegian", value: ELanguage.No },
  { label: "portuguese", value: ELanguage.Pt },
  { label: "swedish", value: ELanguage.Sv },
  { label: "ukrainian", value: ELanguage.Uk },
  { label: "chinese", value: ELanguage.Zh },
];

const languageOptionsAr = [
  { label: "الروسية", value: ELanguage.Ru },
  { label: "إنجليزي", value: ELanguage.En },
  { label: "عربي", value: ELanguage.Ar },
  { label: "البيلاروسية", value: ELanguage.Be },
  { label: "الكاتالونية", value: ELanguage.Ca },
  { label: "التشيكية", value: ELanguage.Cs },
  { label: "الألمانية", value: ELanguage.De },
  { label: "الأسبانية", value: ELanguage.Es },
  { label: "الفنلندية", value: ELanguage.Fi },
  { label: "فرنسي", value: ELanguage.Fr },
  { label: "العبرية", value: ELanguage.He },
  { label: "الكرواتية", value: ELanguage.Hr },
  { label: "المجرية", value: ELanguage.Hu },
  { label: "الاندونيسية", value: ELanguage.Id },
  { label: "ايطالي", value: ELanguage.It },
  { label: "اليابانية", value: ELanguage.Ja },
  { label: "الكازاخستانية", value: ELanguage.Kk },
  { label: "كوري", value: ELanguage.Ko },
  { label: "هولندي", value: ELanguage.Nl },
  { label: "النرويجية", value: ELanguage.No },
  { label: "البرتغالية", value: ELanguage.Pt },
  { label: "السويدية", value: ELanguage.Sv },
  { label: "الأوكرانية", value: ELanguage.Uk },
  { label: "الصينية", value: ELanguage.Zh },
];

const languageOptionsBe = [
  { label: "беларуская", value: ELanguage.Ru },
  { label: "англійская", value: ELanguage.En },
  { label: "арабская", value: ELanguage.Ar },
  { label: "беларуская", value: ELanguage.Be },
  { label: "каталанскі", value: ELanguage.Ca },
  { label: "чэшскі", value: ELanguage.Cs },
  { label: "нямецкая", value: ELanguage.De },
  { label: "іспанскі", value: ELanguage.Es },
  { label: "фінскі", value: ELanguage.Fi },
  { label: "французская", value: ELanguage.Fr },
  { label: "іўрыт", value: ELanguage.He },
  { label: "харвацкая", value: ELanguage.Hr },
  { label: "вугорскі", value: ELanguage.Hu },
  { label: "інданезійская", value: ELanguage.Id },
  { label: "італьянскі", value: ELanguage.It },
  { label: "японскі", value: ELanguage.Ja },
  { label: "казахскі", value: ELanguage.Kk },
  { label: "карэйская", value: ELanguage.Ko },
  { label: "нідэрландская", value: ELanguage.Nl },
  { label: "нарвежская", value: ELanguage.No },
  { label: "партугальская", value: ELanguage.Pt },
  { label: "шведскі", value: ELanguage.Sv },
  { label: "украінскі", value: ELanguage.Uk },
  { label: "кітайскі", value: ELanguage.Zh },
];

const languageOptionsCa = [
  { label: "rus", value: ELanguage.Ru },
  { label: "anglès", value: ELanguage.En },
  { label: "àrab", value: ELanguage.Ar },
  { label: "bielorús", value: ELanguage.Be },
  { label: "català", value: ELanguage.Ca },
  { label: "txec", value: ELanguage.Cs },
  { label: "alemany", value: ELanguage.De },
  { label: "espanyol", value: ELanguage.Es },
  { label: "finès", value: ELanguage.Fi },
  { label: "francès", value: ELanguage.Fr },
  { label: "hebreu", value: ELanguage.He },
  { label: "croat", value: ELanguage.Hr },
  { label: "hongarès", value: ELanguage.Hu },
  { label: "indonesi", value: ELanguage.Id },
  { label: "italià", value: ELanguage.It },
  { label: "japonès", value: ELanguage.Ja },
  { label: "kazakh", value: ELanguage.Kk },
  { label: "coreà", value: ELanguage.Ko },
  { label: "holandès", value: ELanguage.Nl },
  { label: "noruec", value: ELanguage.No },
  { label: "portuguès", value: ELanguage.Pt },
  { label: "suec", value: ELanguage.Sv },
  { label: "ucraïnès", value: ELanguage.Uk },
  { label: "xinès", value: ELanguage.Zh },
];

const languageOptionsCs = [
  { label: "ruština", value: ELanguage.Ru },
  { label: "angličtina", value: ELanguage.En },
  { label: "арабский", value: ELanguage.Ar },
  { label: "arab", value: ELanguage.Be },
  { label: "katalánština", value: ELanguage.Ca },
  { label: "čeština", value: ELanguage.Cs },
  { label: "němec", value: ELanguage.De },
  { label: "španělština", value: ELanguage.Es },
  { label: "finština", value: ELanguage.Fi },
  { label: "francouzština", value: ELanguage.Fr },
  { label: "hebrejština", value: ELanguage.He },
  { label: "chorvatský", value: ELanguage.Hr },
  { label: "maďarský", value: ELanguage.Hu },
  { label: "indonéština", value: ELanguage.Id },
  { label: "italština", value: ELanguage.It },
  { label: "japonský", value: ELanguage.Ja },
  { label: "kazašský", value: ELanguage.Kk },
  { label: "korejština", value: ELanguage.Ko },
  { label: "holandský", value: ELanguage.Nl },
  { label: "norský", value: ELanguage.No },
  { label: "portugalština", value: ELanguage.Pt },
  { label: "švédský", value: ELanguage.Sv },
  { label: "ukrajinština", value: ELanguage.Uk },
  { label: "čínština", value: ELanguage.Zh },
];

const languageOptionsDe = [
  { label: "russisch", value: ELanguage.Ru },
  { label: "englisch", value: ELanguage.En },
  { label: "araber", value: ELanguage.Ar },
  { label: "weißrussisch", value: ELanguage.Be },
  { label: "katalanisch", value: ELanguage.Ca },
  { label: "tschechisch", value: ELanguage.Cs },
  { label: "deutsch", value: ELanguage.De },
  { label: "spanisch", value: ELanguage.Es },
  { label: "finnisch", value: ELanguage.Fi },
  { label: "französisch", value: ELanguage.Fr },
  { label: "hebräisch", value: ELanguage.He },
  { label: "kroatisch", value: ELanguage.Hr },
  { label: "ungarisch", value: ELanguage.Hu },
  { label: "indonesisch", value: ELanguage.Id },
  { label: "italienisch", value: ELanguage.It },
  { label: "japanisch", value: ELanguage.Ja },
  { label: "kasachisch", value: ELanguage.Kk },
  { label: "koreanisch", value: ELanguage.Ko },
  { label: "niederländisch", value: ELanguage.Nl },
  { label: "norwegisch", value: ELanguage.No },
  { label: "portugiesisch", value: ELanguage.Pt },
  { label: "schwedisch", value: ELanguage.Sv },
  { label: "ukrainisch", value: ELanguage.Uk },
  { label: "chinesisch", value: ELanguage.Zh },
];

const languageOptionsEs = [
  { label: "ruso", value: ELanguage.Ru },
  { label: "inglés", value: ELanguage.En },
  { label: "árabe", value: ELanguage.Ar },
  { label: "bielorruso", value: ELanguage.Be },
  { label: "catalán", value: ELanguage.Ca },
  { label: "checo", value: ELanguage.Cs },
  { label: "alemán", value: ELanguage.De },
  { label: "español", value: ELanguage.Es },
  { label: "finlandés", value: ELanguage.Fi },
  { label: "francés", value: ELanguage.Fr },
  { label: "hebreo", value: ELanguage.He },
  { label: "croata", value: ELanguage.Hr },
  { label: "húngaro", value: ELanguage.Hu },
  { label: "indonesio", value: ELanguage.Id },
  { label: "italiano", value: ELanguage.It },
  { label: "japonés", value: ELanguage.Ja },
  { label: "kazajo", value: ELanguage.Kk },
  { label: "coreano", value: ELanguage.Ko },
  { label: "holandés", value: ELanguage.Nl },
  { label: "noruego", value: ELanguage.No },
  { label: "portugués", value: ELanguage.Pt },
  { label: "sueco", value: ELanguage.Sv },
  { label: "ucranio", value: ELanguage.Uk },
  { label: "chino", value: ELanguage.Zh },
];

const languageOptionsFi = [
  { label: "venäjäksi", value: ELanguage.Ru },
  { label: "englanti", value: ELanguage.En },
  { label: "arabi", value: ELanguage.Ar },
  { label: "valko-venäjän", value: ELanguage.Be },
  { label: "katalaani", value: ELanguage.Ca },
  { label: "tšekki", value: ELanguage.Cs },
  { label: "saksaksi", value: ELanguage.De },
  { label: "espanja", value: ELanguage.Es },
  { label: "suomalainen", value: ELanguage.Fi },
  { label: "ranskalainen", value: ELanguage.Fr },
  { label: "heprealainen", value: ELanguage.He },
  { label: "kroatialainen", value: ELanguage.Hr },
  { label: "Unkari", value: ELanguage.Hu },
  { label: "indonesialainen", value: ELanguage.Id },
  { label: "italialainen", value: ELanguage.It },
  { label: "japanilainen", value: ELanguage.Ja },
  { label: "kazakstan", value: ELanguage.Kk },
  { label: "korealainen", value: ELanguage.Ko },
  { label: "hollantilainen", value: ELanguage.Nl },
  { label: "norjalainen", value: ELanguage.No },
  { label: "portugali", value: ELanguage.Pt },
  { label: "ruotsinkielinen", value: ELanguage.Sv },
  { label: "ukrainalainen", value: ELanguage.Uk },
  { label: "kiinalainen", value: ELanguage.Zh },
];

const languageOptionsFr = [
  { label: "russe", value: ELanguage.Ru },
  { label: "anglais", value: ELanguage.En },
  { label: "arabe", value: ELanguage.Ar },
  { label: "biélorusse", value: ELanguage.Be },
  { label: "catalan", value: ELanguage.Ca },
  { label: "tchèque", value: ELanguage.Cs },
  { label: "allemand", value: ELanguage.De },
  { label: "espagnol", value: ELanguage.Es },
  { label: "finlandais", value: ELanguage.Fi },
  { label: "français", value: ELanguage.Fr },
  { label: "hébreu", value: ELanguage.He },
  { label: "croate", value: ELanguage.Hr },
  { label: "hongrois", value: ELanguage.Hu },
  { label: "indonésien", value: ELanguage.Id },
  { label: "italien", value: ELanguage.It },
  { label: "japonais", value: ELanguage.Ja },
  { label: "kazakh", value: ELanguage.Kk },
  { label: "coréen", value: ELanguage.Ko },
  { label: "néerlandais", value: ELanguage.Nl },
  { label: "norvégien", value: ELanguage.No },
  { label: "portugais", value: ELanguage.Pt },
  { label: "suédois", value: ELanguage.Sv },
  { label: "ukrainien", value: ELanguage.Uk },
  { label: "Chinois", value: ELanguage.Zh },
];

const languageOptionsHe = [
  { label: "רוּסִי", value: ELanguage.Ru },
  { label: "אַנגְלִית", value: ELanguage.En },
  { label: "ערבי", value: ELanguage.Ar },
  { label: "ביילורוסית", value: ELanguage.Be },
  { label: "קטלאנית", value: ELanguage.Ca },
  { label: "צ'כית", value: ELanguage.Cs },
  { label: "גֶרמָנִיָת", value: ELanguage.De },
  { label: "סְפָרַדִית", value: ELanguage.Es },
  { label: "פִינִית", value: ELanguage.Fi },
  { label: "צָרְפָתִית", value: ELanguage.Fr },
  { label: "עִברִית", value: ELanguage.He },
  { label: "קרואטית", value: ELanguage.Hr },
  { label: "הוּנגָרִי", value: ELanguage.Hu },
  { label: "אינדונזית", value: ELanguage.Id },
  { label: "אִיטַלְקִית", value: ELanguage.It },
  { label: "יַפָּנִית", value: ELanguage.Ja },
  { label: "קזחית", value: ELanguage.Kk },
  { label: "קוריאנית", value: ELanguage.Ko },
  { label: "הוֹלַנדִי", value: ELanguage.Nl },
  { label: "נורבגית", value: ELanguage.No },
  { label: "פורטוגזית", value: ELanguage.Pt },
  { label: "שוודית", value: ELanguage.Sv },
  { label: "אוקראינית", value: ELanguage.Uk },
  { label: "סִינִית", value: ELanguage.Zh },
];

const languageOptionsHr = [
  { label: "ruski", value: ELanguage.Ru },
  { label: "engleski", value: ELanguage.En },
  { label: "arapski", value: ELanguage.Ar },
  { label: "bjeloruski", value: ELanguage.Be },
  { label: "katalonski", value: ELanguage.Ca },
  { label: "češki", value: ELanguage.Cs },
  { label: "njemački", value: ELanguage.De },
  { label: "španjolski", value: ELanguage.Es },
  { label: "finski", value: ELanguage.Fi },
  { label: "francuski", value: ELanguage.Fr },
  { label: "hebrejski", value: ELanguage.He },
  { label: "hrvatski", value: ELanguage.Hr },
  { label: "mađarski", value: ELanguage.Hu },
  { label: "indonezijski", value: ELanguage.Id },
  { label: "talijanski", value: ELanguage.It },
  { label: "japanski", value: ELanguage.Ja },
  { label: "kazahstanski", value: ELanguage.Kk },
  { label: "korejski", value: ELanguage.Ko },
  { label: "nizozemski", value: ELanguage.Nl },
  { label: "norveški", value: ELanguage.No },
  { label: "portugalski", value: ELanguage.Pt },
  { label: "švedski", value: ELanguage.Sv },
  { label: "ukrajinski", value: ELanguage.Uk },
  { label: "kineski", value: ELanguage.Zh },
];

const languageOptionsHu = [
  { label: "orosz", value: ELanguage.Ru },
  { label: "angol", value: ELanguage.En },
  { label: "arab", value: ELanguage.Ar },
  { label: "fehérorosz", value: ELanguage.Be },
  { label: "katalán", value: ELanguage.Ca },
  { label: "cseh", value: ELanguage.Cs },
  { label: "német", value: ELanguage.De },
  { label: "spanyol", value: ELanguage.Es },
  { label: "finn", value: ELanguage.Fi },
  { label: "francia", value: ELanguage.Fr },
  { label: "héber", value: ELanguage.He },
  { label: "horvát", value: ELanguage.Hr },
  { label: "magyar", value: ELanguage.Hu },
  { label: "indonéz", value: ELanguage.Id },
  { label: "olasz", value: ELanguage.It },
  { label: "japán", value: ELanguage.Ja },
  { label: "kazah", value: ELanguage.Kk },
  { label: "holland", value: ELanguage.Nl },
  { label: "norvég", value: ELanguage.No },
  { label: "portugál", value: ELanguage.Pt },
  { label: "svéd", value: ELanguage.Sv },
  { label: "ukrán", value: ELanguage.Uk },
  { label: "kínai", value: ELanguage.Zh },
];

const languageOptionsId = [
  { label: "rusia", value: ELanguage.Ru },
  { label: "bahasa inggris", value: ELanguage.En },
  { label: "arab", value: ELanguage.Ar },
  { label: "белорусский", value: ELanguage.Be },
  { label: "belarusia", value: ELanguage.Ca },
  { label: "ceko", value: ELanguage.Cs },
  { label: "jerman", value: ELanguage.De },
  { label: "spanyol", value: ELanguage.Es },
  { label: "finlandia", value: ELanguage.Fi },
  { label: "perancis", value: ELanguage.Fr },
  { label: "ibrani", value: ELanguage.He },
  { label: "kroasia", value: ELanguage.Hr },
  { label: "hongaria", value: ELanguage.Hu },
  { label: "indonesia", value: ELanguage.Id },
  { label: "italia", value: ELanguage.It },
  { label: "jepang", value: ELanguage.Ja },
  { label: "kazakh", value: ELanguage.Kk },
  { label: "korea", value: ELanguage.Ko },
  { label: "belanda", value: ELanguage.Nl },
  { label: "norwegia", value: ELanguage.No },
  { label: "portugis", value: ELanguage.Pt },
  { label: "swedia", value: ELanguage.Sv },
  { label: "ukraina", value: ELanguage.Uk },
  { label: "cina", value: ELanguage.Zh },
];

const languageOptionsIt = [
  { label: "russo", value: ELanguage.Ru },
  { label: "inglese", value: ELanguage.En },
  { label: "арабский", value: ELanguage.Ar },
  { label: "arabo", value: ELanguage.Be },
  { label: "catalano", value: ELanguage.Ca },
  { label: "ceco", value: ELanguage.Cs },
  { label: "tedesco", value: ELanguage.De },
  { label: "spagnolo", value: ELanguage.Es },
  { label: "finlandese", value: ELanguage.Fi },
  { label: "francese", value: ELanguage.Fr },
  { label: "ebraico", value: ELanguage.He },
  { label: "croato", value: ELanguage.Hr },
  { label: "ungherese", value: ELanguage.Hu },
  { label: "indonesiano", value: ELanguage.Id },
  { label: "italiano", value: ELanguage.It },
  { label: "giapponese", value: ELanguage.Ja },
  { label: "kazakiistan", value: ELanguage.Kk },
  { label: "coreano", value: ELanguage.Ko },
  { label: "olandese", value: ELanguage.Nl },
  { label: "norvegese", value: ELanguage.No },
  { label: "portoghese", value: ELanguage.Pt },
  { label: "svedese", value: ELanguage.Sv },
  { label: "ucraino", value: ELanguage.Uk },
  { label: "cinese", value: ELanguage.Zh },
];

const languageOptionsJa = [
  { label: "ロシア", value: ELanguage.Ru },
  { label: "英語", value: ELanguage.En },
  { label: "アラブ", value: ELanguage.Ar },
  { label: "ベラルーシ語", value: ELanguage.Be },
  { label: "カタルーニャ語", value: ELanguage.Ca },
  { label: "チェコ語", value: ELanguage.Cs },
  { label: "ドイツ語", value: ELanguage.De },
  { label: "スペイン語", value: ELanguage.Es },
  { label: "フィンランド語", value: ELanguage.Fi },
  { label: "フランス語", value: ELanguage.Fr },
  { label: "ヘブライ語", value: ELanguage.He },
  { label: "クロアチア語", value: ELanguage.Hr },
  { label: "ハンガリー語", value: ELanguage.Hu },
  { label: "インドネシア語", value: ELanguage.Id },
  { label: "イタリア語", value: ELanguage.It },
  { label: "日本語", value: ELanguage.Ja },
  { label: "カザフ語", value: ELanguage.Kk },
  { label: "韓国語", value: ELanguage.Ko },
  { label: "オランダ語", value: ELanguage.Nl },
  { label: "ノルウェー語", value: ELanguage.No },
  { label: "ポルトガル語", value: ELanguage.Pt },
  { label: "スウェーデン語", value: ELanguage.Sv },
  { label: "ウクライナ語", value: ELanguage.Uk },
  { label: "中国語", value: ELanguage.Zh },
];

const languageOptionsKk = [
  { label: "орыс", value: ELanguage.Ru },
  { label: "ағылшынша", value: ELanguage.En },
  { label: "араб", value: ELanguage.Ar },
  { label: "белорус", value: ELanguage.Be },
  { label: "каталон", value: ELanguage.Ca },
  { label: "чех", value: ELanguage.Cs },
  { label: "неміс", value: ELanguage.De },
  { label: "испан", value: ELanguage.Es },
  { label: "фин", value: ELanguage.Fi },
  { label: "француз", value: ELanguage.Fr },
  { label: "иврит", value: ELanguage.He },
  { label: "хорват", value: ELanguage.Hr },
  { label: "венгр", value: ELanguage.Hu },
  { label: "индонезиялық", value: ELanguage.Id },
  { label: "итальян", value: ELanguage.It },
  { label: "жапон", value: ELanguage.Ja },
  { label: "қазақ", value: ELanguage.Kk },
  { label: "корей", value: ELanguage.Ko },
  { label: "голланд", value: ELanguage.Nl },
  { label: "норвег", value: ELanguage.No },
  { label: "португал", value: ELanguage.Pt },
  { label: "швед", value: ELanguage.Sv },
  { label: "украин", value: ELanguage.Uk },
  { label: "қытай", value: ELanguage.Zh },
];

const languageOptionsKo = [
  { label: "러시아인", value: ELanguage.Ru },
  { label: "영어", value: ELanguage.En },
  { label: "아라비아 사람", value: ELanguage.Ar },
  { label: "아라비아 사람", value: ELanguage.Be },
  { label: "카탈로니아 사람", value: ELanguage.Ca },
  { label: "체코 사람", value: ELanguage.Cs },
  { label: "독일 사람", value: ELanguage.De },
  { label: "스페인 사람", value: ELanguage.Es },
  { label: "핀란드어", value: ELanguage.Fi },
  { label: "프랑스 국민", value: ELanguage.Fr },
  { label: "헤브라이 사람", value: ELanguage.He },
  { label: "크로아티아어", value: ELanguage.Hr },
  { label: "헝가리 인", value: ELanguage.Hu },
  { label: "인도네시아 인", value: ELanguage.Id },
  { label: "이탈리아 사람", value: ELanguage.It },
  { label: "японский", value: ELanguage.Ja },
  { label: "카자흐어", value: ELanguage.Kk },
  { label: "한국인", value: ELanguage.Ko },
  { label: "네덜란드 사람", value: ELanguage.Nl },
  { label: "노르웨이 인", value: ELanguage.No },
  { label: "포르투갈 인", value: ELanguage.Pt },
  { label: "스웨덴어", value: ELanguage.Sv },
  { label: "우크라이나 말", value: ELanguage.Uk },
  { label: "중국인", value: ELanguage.Zh },
];

const languageOptionsNl = [
  { label: "russisch", value: ELanguage.Ru },
  { label: "engels", value: ELanguage.En },
  { label: "arabisch", value: ELanguage.Ar },
  { label: "wit-russisch", value: ELanguage.Be },
  { label: "catalaans", value: ELanguage.Ca },
  { label: "tsjechisch", value: ELanguage.Cs },
  { label: "duits", value: ELanguage.De },
  { label: "spaans", value: ELanguage.Es },
  { label: "fins", value: ELanguage.Fi },
  { label: "frans", value: ELanguage.Fr },
  { label: "hebreeuws", value: ELanguage.He },
  { label: "kroatisch", value: ELanguage.Hr },
  { label: "hongaars", value: ELanguage.Hu },
  { label: "indonesia", value: ELanguage.Id },
  { label: "italia", value: ELanguage.It },
  { label: "japanse", value: ELanguage.Ja },
  { label: "kazakh", value: ELanguage.Kk },
  { label: "korea", value: ELanguage.Ko },
  { label: "belanda", value: ELanguage.Nl },
  { label: "noors", value: ELanguage.No },
  { label: "portugees", value: ELanguage.Pt },
  { label: "zweeds", value: ELanguage.Sv },
  { label: "oekraïens", value: ELanguage.Uk },
  { label: "chinese", value: ELanguage.Zh },
];

const languageOptionsNo = [
  { label: "russisk", value: ELanguage.Ru },
  { label: "engelsk", value: ELanguage.En },
  { label: "arabisk", value: ELanguage.Ar },
  { label: "hviterussisk", value: ELanguage.Be },
  { label: "katalansk", value: ELanguage.Ca },
  { label: "tsjekkisk", value: ELanguage.Cs },
  { label: "tysk", value: ELanguage.De },
  { label: "spansk", value: ELanguage.Es },
  { label: "finsk", value: ELanguage.Fi },
  { label: "fransk", value: ELanguage.Fr },
  { label: "hebraisk", value: ELanguage.He },
  { label: "kroatisk", value: ELanguage.Hr },
  { label: "ungarsk", value: ELanguage.Hu },
  { label: "indonesisk", value: ELanguage.Id },
  { label: "italiensk", value: ELanguage.It },
  { label: "яjapansk", value: ELanguage.Ja },
  { label: "kasakhisk", value: ELanguage.Kk },
  { label: "koreansk", value: ELanguage.Ko },
  { label: "nederlandsk", value: ELanguage.Nl },
  { label: "norsk", value: ELanguage.No },
  { label: "portugisisk", value: ELanguage.Pt },
  { label: "svensk", value: ELanguage.Sv },
  { label: "ukrainsk", value: ELanguage.Uk },
  { label: "kinesisk", value: ELanguage.Zh },
];

const languageOptionsPt = [
  { label: "russo", value: ELanguage.Ru },
  { label: "inglês", value: ELanguage.En },
  { label: "árabe", value: ELanguage.Ar },
  { label: "bielorrusso", value: ELanguage.Be },
  { label: "catalão", value: ELanguage.Ca },
  { label: "tcheco", value: ELanguage.Cs },
  { label: "alemão", value: ELanguage.De },
  { label: "espanhol", value: ELanguage.Es },
  { label: "finlandês", value: ELanguage.Fi },
  { label: "francês", value: ELanguage.Fr },
  { label: "hebraico", value: ELanguage.He },
  { label: "croata", value: ELanguage.Hr },
  { label: "húngaro", value: ELanguage.Hu },
  { label: "indonésio", value: ELanguage.Id },
  { label: "italiano", value: ELanguage.It },
  { label: "japonês", value: ELanguage.Ja },
  { label: "cazaque", value: ELanguage.Kk },
  { label: "coreano", value: ELanguage.Ko },
  { label: "holandês", value: ELanguage.Nl },
  { label: "norueguês", value: ELanguage.No },
  { label: "português", value: ELanguage.Pt },
  { label: "sueco", value: ELanguage.Sv },
  { label: "ucraniano", value: ELanguage.Uk },
  { label: "chinês", value: ELanguage.Zh },
];

const languageOptionsSv = [
  { label: "ryska", value: ELanguage.Ru },
  { label: "engelska", value: ELanguage.En },
  { label: "arab", value: ELanguage.Ar },
  { label: "vitryska", value: ELanguage.Be },
  { label: "katalanska", value: ELanguage.Ca },
  { label: "tjeckiska", value: ELanguage.Cs },
  { label: "tyska", value: ELanguage.De },
  { label: "spanska", value: ELanguage.Es },
  { label: "finska", value: ELanguage.Fi },
  { label: "franska", value: ELanguage.Fr },
  { label: "hebreiska", value: ELanguage.He },
  { label: "kroatisk", value: ELanguage.Hr },
  { label: "ungerska", value: ELanguage.Hu },
  { label: "indonesiska", value: ELanguage.Id },
  { label: "italienska", value: ELanguage.It },
  { label: "japanska", value: ELanguage.Ja },
  { label: "kazakiska", value: ELanguage.Kk },
  { label: "koreanska", value: ELanguage.Ko },
  { label: "holländska", value: ELanguage.Nl },
  { label: "norska", value: ELanguage.No },
  { label: "portugisiska", value: ELanguage.Pt },
  { label: "svenska", value: ELanguage.Sv },
  { label: "ukrainska", value: ELanguage.Uk },
  { label: "kinesiska", value: ELanguage.Zh },
];

const languageOptionsUk = [
  { label: "російська", value: ELanguage.Ru },
  { label: "англійська", value: ELanguage.En },
  { label: "арабська", value: ELanguage.Ar },
  { label: "білоруська", value: ELanguage.Be },
  { label: "каталанський", value: ELanguage.Ca },
  { label: "чеська", value: ELanguage.Cs },
  { label: "німецька", value: ELanguage.De },
  { label: "іспанська", value: ELanguage.Es },
  { label: "фінська", value: ELanguage.Fi },
  { label: "французька", value: ELanguage.Fr },
  { label: "іврит", value: ELanguage.He },
  { label: "хорватська", value: ELanguage.Hr },
  { label: "угорська", value: ELanguage.Hu },
  { label: "індонезійська", value: ELanguage.Id },
  { label: "італійська", value: ELanguage.It },
  { label: "японська", value: ELanguage.Ja },
  { label: "казахська", value: ELanguage.Kk },
  { label: "корейська", value: ELanguage.Ko },
  { label: "нідерландська", value: ELanguage.Nl },
  { label: "норвезька", value: ELanguage.No },
  { label: "португальська", value: ELanguage.Pt },
  { label: "шведська", value: ELanguage.Sv },
  { label: "українська", value: ELanguage.Uk },
  { label: "китайська", value: ELanguage.Zh },
];

const languageOptionsZh = [
  { label: "俄语", value: ELanguage.Ru },
  { label: "英语", value: ELanguage.En },
  { label: "阿拉伯", value: ELanguage.Ar },
  { label: "白俄罗斯语", value: ELanguage.Be },
  { label: "加泰罗尼亚语", value: ELanguage.Ca },
  { label: "捷克语", value: ELanguage.Cs },
  { label: "德语", value: ELanguage.De },
  { label: "西班牙语", value: ELanguage.Es },
  { label: "芬兰", value: ELanguage.Fi },
  { label: "法语", value: ELanguage.Fr },
  { label: "希伯来语", value: ELanguage.He },
  { label: "克罗地亚语", value: ELanguage.Hr },
  { label: "匈牙利", value: ELanguage.Hu },
  { label: "印度尼西亚", value: ELanguage.Id },
  { label: "意大利语", value: ELanguage.It },
  { label: "日本人", value: ELanguage.Ja },
  { label: "哈萨克语", value: ELanguage.Kk },
  { label: "韩国人", value: ELanguage.Ko },
  { label: "荷兰语", value: ELanguage.Nl },
  { label: "挪威", value: ELanguage.No },
  { label: "葡萄牙语", value: ELanguage.Pt },
  { label: "瑞典", value: ELanguage.Sv },
  { label: "乌克兰", value: ELanguage.Uk },
  { label: "中国人", value: ELanguage.Zh },
];

export const LANGUAGE_MAPPING = {
  [ELanguage.Ru]: languageOptionsRu,
  [ELanguage.En]: languageOptionsEn,
  [ELanguage.Ar]: languageOptionsAr,
  [ELanguage.Be]: languageOptionsBe,
  [ELanguage.Ca]: languageOptionsCa,
  [ELanguage.Cs]: languageOptionsCs,
  [ELanguage.De]: languageOptionsDe,
  [ELanguage.Es]: languageOptionsEs,
  [ELanguage.Fi]: languageOptionsFi,
  [ELanguage.Fr]: languageOptionsFr,
  [ELanguage.He]: languageOptionsHe,
  [ELanguage.Hr]: languageOptionsHr,
  [ELanguage.Hu]: languageOptionsHu,
  [ELanguage.Id]: languageOptionsId,
  [ELanguage.It]: languageOptionsIt,
  [ELanguage.Ja]: languageOptionsJa,
  [ELanguage.Kk]: languageOptionsKk,
  [ELanguage.Ko]: languageOptionsKo,
  [ELanguage.Nl]: languageOptionsNl,
  [ELanguage.No]: languageOptionsNo,
  [ELanguage.Pt]: languageOptionsPt,
  [ELanguage.Sv]: languageOptionsSv,
  [ELanguage.Uk]: languageOptionsUk,
  [ELanguage.Zh]: languageOptionsZh,
};

export const LOCALE_MAPPING = {
  [ELanguage.Ru]: ru,
  [ELanguage.En]: enUS,
};
