import { enUS, ru } from "date-fns/locale";
import { ELanguage } from "@/app/shared/enums";

const languageOptionsRu = [
  { label: "русский", value: ELanguage.Ru },
  { label: "английский", value: ELanguage.En },
  { label: "арабский", value: ELanguage.Ar },
  { label: "белорусский", value: ELanguage.Be },
  { label: "каталанский", value: ELanguage.Ca },
  { label: "чешский", value: ELanguage.Cs },
  { label: "немецкий", value: ELanguage.De },
  { label: "финский", value: ELanguage.Fi },
  { label: "французский", value: ELanguage.Fr },
  { label: "иврит", value: ELanguage.He },
  { label: "хорватский", value: ELanguage.Hr },
  { label: "венгерский", value: ELanguage.Hu },
  { label: "индонезийский", value: ELanguage.Id },
  { label: "итальянский", value: ELanguage.It },
  { label: "казахский", value: ELanguage.Kk },
  { label: "корейский", value: ELanguage.Ko },
  { label: "нидерладский", value: ELanguage.Nl },
];

const languageOptionsEn = [
  { label: "russian", value: ELanguage.Ru },
  { label: "english", value: ELanguage.En },
  { label: "arab", value: ELanguage.Ar },
  { label: "belorussian", value: ELanguage.Be },
  { label: "catalan", value: ELanguage.Ca },
  { label: "czech", value: ELanguage.Cs },
  { label: "german", value: ELanguage.De },
  { label: "finnish", value: ELanguage.Fi },
  { label: "french", value: ELanguage.Fr },
  { label: "hebrew", value: ELanguage.He },
  { label: "croatian", value: ELanguage.Hr },
  { label: "hungarian", value: ELanguage.Hu },
  { label: "indonesian", value: ELanguage.Id },
  { label: "italian", value: ELanguage.It },
  { label: "kazakh", value: ELanguage.Kk },
  { label: "korean", value: ELanguage.Ko },
  { label: "dutch", value: ELanguage.Nl },
];

const languageOptionsAr = [
  { label: "الروسية", value: ELanguage.Ru },
  { label: "إنجليزي", value: ELanguage.En },
  { label: "عربي", value: ELanguage.Ar },
  { label: "البيلاروسية", value: ELanguage.Be },
  { label: "الكاتالونية", value: ELanguage.Ca },
  { label: "التشيكية", value: ELanguage.Cs },
  { label: "الألمانية", value: ELanguage.De },
  { label: "الفنلندية", value: ELanguage.Fi },
  { label: "فرنسي", value: ELanguage.Fr },
  { label: "العبرية", value: ELanguage.He },
  { label: "الكرواتية", value: ELanguage.Hr },
  { label: "المجرية", value: ELanguage.Hu },
  { label: "الاندونيسية", value: ELanguage.Id },
  { label: "ايطالي", value: ELanguage.It },
  { label: "الكازاخستانية", value: ELanguage.Kk },
  { label: "كوري", value: ELanguage.Ko },
  { label: "هولندي", value: ELanguage.Nl },
];

const languageOptionsBe = [
  { label: "беларуская", value: ELanguage.Ru },
  { label: "англійская", value: ELanguage.En },
  { label: "арабская", value: ELanguage.Ar },
  { label: "беларуская", value: ELanguage.Be },
  { label: "каталанскі", value: ELanguage.Ca },
  { label: "чэшскі", value: ELanguage.Cs },
  { label: "нямецкая", value: ELanguage.De },
  { label: "фінскі", value: ELanguage.Fi },
  { label: "французская", value: ELanguage.Fr },
  { label: "іўрыт", value: ELanguage.He },
  { label: "харвацкая", value: ELanguage.Hr },
  { label: "вугорскі", value: ELanguage.Hu },
  { label: "інданезійская", value: ELanguage.Id },
  { label: "італьянскі", value: ELanguage.It },
  { label: "казахскі", value: ELanguage.Kk },
  { label: "карэйская", value: ELanguage.Ko },
  { label: "нідэрладскі", value: ELanguage.Nl },
];

const languageOptionsCa = [
  { label: "rus", value: ELanguage.Ru },
  { label: "anglès", value: ELanguage.En },
  { label: "àrab", value: ELanguage.Ar },
  { label: "bielorús", value: ELanguage.Be },
  { label: "català", value: ELanguage.Ca },
  { label: "txec", value: ELanguage.Cs },
  { label: "alemany", value: ELanguage.De },
  { label: "finès", value: ELanguage.Fi },
  { label: "francès", value: ELanguage.Fr },
  { label: "hebreu", value: ELanguage.He },
  { label: "croat", value: ELanguage.Hr },
  { label: "hongarès", value: ELanguage.Hu },
  { label: "indonesi", value: ELanguage.Id },
  { label: "italià", value: ELanguage.It },
  { label: "kazakh", value: ELanguage.Kk },
  { label: "coreà", value: ELanguage.Ko },
  { label: "holandès", value: ELanguage.Nl },
];

const languageOptionsCs = [
  { label: "ruština", value: ELanguage.Ru },
  { label: "angličtina", value: ELanguage.En },
  { label: "арабский", value: ELanguage.Ar },
  { label: "arab", value: ELanguage.Be },
  { label: "katalánština", value: ELanguage.Ca },
  { label: "čeština", value: ELanguage.Cs },
  { label: "němec", value: ELanguage.De },
  { label: "finština", value: ELanguage.Fi },
  { label: "francouzština", value: ELanguage.Fr },
  { label: "hebrejština", value: ELanguage.He },
  { label: "chorvatský", value: ELanguage.Hr },
  { label: "maďarský", value: ELanguage.Hu },
  { label: "indonéština", value: ELanguage.Id },
  { label: "italština", value: ELanguage.It },
  { label: "kazašský", value: ELanguage.Kk },
  { label: "korejština", value: ELanguage.Ko },
  { label: "holandský", value: ELanguage.Nl },
];

const languageOptionsDe = [
  { label: "russisch", value: ELanguage.Ru },
  { label: "englisch", value: ELanguage.En },
  { label: "araber", value: ELanguage.Ar },
  { label: "weißrussisch", value: ELanguage.Be },
  { label: "katalanisch", value: ELanguage.Ca },
  { label: "tschechisch", value: ELanguage.Cs },
  { label: "deutsch", value: ELanguage.De },
  { label: "finnisch", value: ELanguage.Fi },
  { label: "französisch", value: ELanguage.Fr },
  { label: "hebräisch", value: ELanguage.He },
  { label: "kroatisch", value: ELanguage.Hr },
  { label: "ungarisch", value: ELanguage.Hu },
  { label: "indonesisch", value: ELanguage.Id },
  { label: "italienisch", value: ELanguage.It },
  { label: "kasachisch", value: ELanguage.Kk },
  { label: "koreanisch", value: ELanguage.Ko },
  { label: "niederländisch", value: ELanguage.Nl },
];

const languageOptionsFi = [
  { label: "venäjäksi", value: ELanguage.Ru },
  { label: "englanti", value: ELanguage.En },
  { label: "arabi", value: ELanguage.Ar },
  { label: "valko-venäjän", value: ELanguage.Be },
  { label: "katalaani", value: ELanguage.Ca },
  { label: "tšekki", value: ELanguage.Cs },
  { label: "saksaksi", value: ELanguage.De },
  { label: "suomalainen", value: ELanguage.Fi },
  { label: "ranskalainen", value: ELanguage.Fr },
  { label: "heprealainen", value: ELanguage.He },
  { label: "kroatialainen", value: ELanguage.Hr },
  { label: "Unkari", value: ELanguage.Hu },
  { label: "indonesialainen", value: ELanguage.Id },
  { label: "italialainen", value: ELanguage.It },
  { label: "kazakstan", value: ELanguage.Kk },
  { label: "korealainen", value: ELanguage.Ko },
  { label: "hollantilainen", value: ELanguage.Nl },
];

const languageOptionsFr = [
  { label: "russe", value: ELanguage.Ru },
  { label: "anglais", value: ELanguage.En },
  { label: "arabe", value: ELanguage.Ar },
  { label: "biélorusse", value: ELanguage.Be },
  { label: "catalan", value: ELanguage.Ca },
  { label: "tchèque", value: ELanguage.Cs },
  { label: "allemand", value: ELanguage.De },
  { label: "finlandais", value: ELanguage.Fi },
  { label: "français", value: ELanguage.Fr },
  { label: "hébreu", value: ELanguage.He },
  { label: "croate", value: ELanguage.Hr },
  { label: "hongrois", value: ELanguage.Hu },
  { label: "indonésien", value: ELanguage.Id },
  { label: "italien", value: ELanguage.It },
  { label: "kazakh", value: ELanguage.Kk },
  { label: "coréen", value: ELanguage.Ko },
  { label: "néerlandais", value: ELanguage.Nl },
];

const languageOptionsHe = [
  { label: "רוּסִי", value: ELanguage.Ru },
  { label: "אַנגְלִית", value: ELanguage.En },
  { label: "ערבי", value: ELanguage.Ar },
  { label: "ביילורוסית", value: ELanguage.Be },
  { label: "קטלאנית", value: ELanguage.Ca },
  { label: "צ'כית", value: ELanguage.Cs },
  { label: "גֶרמָנִיָת", value: ELanguage.De },
  { label: "פִינִית", value: ELanguage.Fi },
  { label: "צָרְפָתִית", value: ELanguage.Fr },
  { label: "עִברִית", value: ELanguage.He },
  { label: "קרואטית", value: ELanguage.Hr },
  { label: "הוּנגָרִי", value: ELanguage.Hu },
  { label: "אינדונזית", value: ELanguage.Id },
  { label: "אִיטַלְקִית", value: ELanguage.It },
  { label: "קזחית", value: ELanguage.Kk },
  { label: "קוריאנית", value: ELanguage.Ko },
  { label: "הוֹלַנדִי", value: ELanguage.Nl },
];

const languageOptionsHr = [
  { label: "ruski", value: ELanguage.Ru },
  { label: "engleski", value: ELanguage.En },
  { label: "arapski", value: ELanguage.Ar },
  { label: "bjeloruski", value: ELanguage.Be },
  { label: "katalonski", value: ELanguage.Ca },
  { label: "češki", value: ELanguage.Cs },
  { label: "njemački", value: ELanguage.De },
  { label: "finski", value: ELanguage.Fi },
  { label: "francuski", value: ELanguage.Fr },
  { label: "hebrejski", value: ELanguage.He },
  { label: "hrvatski", value: ELanguage.Hr },
  { label: "mađarski", value: ELanguage.Hu },
  { label: "indonezijski", value: ELanguage.Id },
  { label: "talijanski", value: ELanguage.It },
  { label: "kazahstanski", value: ELanguage.Kk },
  { label: "korejski", value: ELanguage.Ko },
  { label: "nizozemski", value: ELanguage.Nl },
];

const languageOptionsHu = [
  { label: "orosz", value: ELanguage.Ru },
  { label: "angol", value: ELanguage.En },
  { label: "arab", value: ELanguage.Ar },
  { label: "fehérorosz", value: ELanguage.Be },
  { label: "katalán", value: ELanguage.Ca },
  { label: "cseh", value: ELanguage.Cs },
  { label: "német", value: ELanguage.De },
  { label: "finn", value: ELanguage.Fi },
  { label: "francia", value: ELanguage.Fr },
  { label: "héber", value: ELanguage.He },
  { label: "horvát", value: ELanguage.Hr },
  { label: "magyar", value: ELanguage.Hu },
  { label: "indonéz", value: ELanguage.Id },
  { label: "olasz", value: ELanguage.It },
  { label: "kazah", value: ELanguage.Kk },
  { label: "holland", value: ELanguage.Nl },
];

const languageOptionsId = [
  { label: "rusia", value: ELanguage.Ru },
  { label: "bahasa inggris", value: ELanguage.En },
  { label: "arab", value: ELanguage.Ar },
  { label: "белорусский", value: ELanguage.Be },
  { label: "belarusia", value: ELanguage.Ca },
  { label: "ceko", value: ELanguage.Cs },
  { label: "jerman", value: ELanguage.De },
  { label: "finlandia", value: ELanguage.Fi },
  { label: "perancis", value: ELanguage.Fr },
  { label: "ibrani", value: ELanguage.He },
  { label: "kroasia", value: ELanguage.Hr },
  { label: "hongaria", value: ELanguage.Hu },
  { label: "indonesia", value: ELanguage.Id },
  { label: "italia", value: ELanguage.It },
  { label: "kazakh", value: ELanguage.Kk },
  { label: "korea", value: ELanguage.Ko },
  { label: "belanda", value: ELanguage.Nl },
];

const languageOptionsIt = [
  { label: "russo", value: ELanguage.Ru },
  { label: "inglese", value: ELanguage.En },
  { label: "арабский", value: ELanguage.Ar },
  { label: "arabo", value: ELanguage.Be },
  { label: "catalano", value: ELanguage.Ca },
  { label: "ceco", value: ELanguage.Cs },
  { label: "tedesco", value: ELanguage.De },
  { label: "finlandese", value: ELanguage.Fi },
  { label: "francese", value: ELanguage.Fr },
  { label: "ebraico", value: ELanguage.He },
  { label: "croato", value: ELanguage.Hr },
  { label: "ungherese", value: ELanguage.Hu },
  { label: "indonesiano", value: ELanguage.Id },
  { label: "italiano", value: ELanguage.It },
  { label: "kazakiistan", value: ELanguage.Kk },
  { label: "coreano", value: ELanguage.Ko },
  { label: "olandese", value: ELanguage.Nl },
];

const languageOptionsKk = [
  { label: "орыс", value: ELanguage.Ru },
  { label: "ағылшынша", value: ELanguage.En },
  { label: "араб", value: ELanguage.Ar },
  { label: "белорус", value: ELanguage.Be },
  { label: "каталон", value: ELanguage.Ca },
  { label: "чех", value: ELanguage.Cs },
  { label: "неміс", value: ELanguage.De },
  { label: "фин", value: ELanguage.Fi },
  { label: "француз", value: ELanguage.Fr },
  { label: "иврит", value: ELanguage.He },
  { label: "хорват", value: ELanguage.Hr },
  { label: "венгр", value: ELanguage.Hu },
  { label: "индонезиялық", value: ELanguage.Id },
  { label: "итальян", value: ELanguage.It },
  { label: "қазақ", value: ELanguage.Kk },
  { label: "корей", value: ELanguage.Ko },
  { label: "голланд", value: ELanguage.Nl },
];

const languageOptionsKo = [
  { label: "러시아인", value: ELanguage.Ru },
  { label: "영어", value: ELanguage.En },
  { label: "арабский", value: ELanguage.Ar },
  { label: "아라비아 사람", value: ELanguage.Be },
  { label: "카탈로니아 사람", value: ELanguage.Ca },
  { label: "체코 사람", value: ELanguage.Cs },
  { label: "독일 사람", value: ELanguage.De },
  { label: "핀란드어", value: ELanguage.Fi },
  { label: "프랑스 국민", value: ELanguage.Fr },
  { label: "헤브라이 사람", value: ELanguage.He },
  { label: "크로아티아어", value: ELanguage.Hr },
  { label: "헝가리 인", value: ELanguage.Hu },
  { label: "인도네시아 인", value: ELanguage.Id },
  { label: "이탈리아 사람", value: ELanguage.It },
  { label: "카자흐어", value: ELanguage.Kk },
  { label: "한국인", value: ELanguage.Ko },
  { label: "네덜란드 사람", value: ELanguage.Nl },
];

const languageOptionsNl = [
  { label: "russisch", value: ELanguage.Ru },
  { label: "engels", value: ELanguage.En },
  { label: "arabisch", value: ELanguage.Ar },
  { label: "wit-russisch", value: ELanguage.Be },
  { label: "catalaans", value: ELanguage.Ca },
  { label: "tsjechisch", value: ELanguage.Cs },
  { label: "duits", value: ELanguage.De },
  { label: "fins", value: ELanguage.Fi },
  { label: "frans", value: ELanguage.Fr },
  { label: "hebreeuws", value: ELanguage.He },
  { label: "kroatisch", value: ELanguage.Hr },
  { label: "hongaars", value: ELanguage.Hu },
  { label: "indonesia", value: ELanguage.Id },
  { label: "italia", value: ELanguage.It },
  { label: "kazakh", value: ELanguage.Kk },
  { label: "korea", value: ELanguage.Ko },
  { label: "belanda", value: ELanguage.Nl },
];

export const LANGUAGE_MAPPING = {
  [ELanguage.Ru]: languageOptionsRu,
  [ELanguage.En]: languageOptionsEn,
  [ELanguage.Ar]: languageOptionsAr,
  [ELanguage.Be]: languageOptionsBe,
  [ELanguage.Ca]: languageOptionsCa,
  [ELanguage.Cs]: languageOptionsCs,
  [ELanguage.De]: languageOptionsDe,
  [ELanguage.Fi]: languageOptionsFi,
  [ELanguage.Fr]: languageOptionsFr,
  [ELanguage.He]: languageOptionsHe,
  [ELanguage.Hr]: languageOptionsHr,
  [ELanguage.Hu]: languageOptionsHu,
  [ELanguage.Id]: languageOptionsId,
  [ELanguage.It]: languageOptionsIt,
  [ELanguage.Kk]: languageOptionsKk,
  [ELanguage.Ko]: languageOptionsKo,
  [ELanguage.Nl]: languageOptionsNl,
};

export const LOCALE_MAPPING = {
  [ELanguage.Ru]: ru,
  [ELanguage.En]: enUS,
};
