import {
  EMPTY_FIELD_ERROR_MESSAGE,
  FILE_MAX_AMOUNT_MESSAGE,
  FILE_MAX_SIZE_MESSAGE,
  FILE_TYPE_MESSAGE,
  LETTERS_EN,
  LETTERS_RU,
  NAME_ERROR_MESSAGE,
  NAME_REGEXP,
} from "./constants";

export {
  EMPTY_FIELD_ERROR_MESSAGE,
  FILE_MAX_AMOUNT_MESSAGE,
  FILE_MAX_SIZE_MESSAGE,
  FILE_TYPE_MESSAGE,
  LETTERS_EN,
  LETTERS_RU,
  NAME_ERROR_MESSAGE,
  NAME_REGEXP,
};
