export enum EProfileAddFormFields {
  SessionId = "sessionId",
  DisplayName = "displayName",
  Birthday = "birthday",
  Gender = "gender",
  SearchGender = "searchGender",
  Location = "location",
  Description = "description",
  Height = "height",
  Weight = "weight",
  LookingFor = "lookingFor",
  Image = "image",
  TelegramUserID = "telegramUserId",
  TelegramUsername = "telegramUsername",
  TelegramFirstName = "telegramFirstName",
  TelegramLastName = "telegramLastName",
  TelegramLanguageCode = "telegramLanguageCode",
  TelegramAllowsWriteToPm = "telegramAllowsWriteToPm",
  TelegramQueryId = "telegramQueryId",
  Latitude = "latitude",
  Longitude = "longitude",
  AgeFrom = "ageFrom",
  AgeTo = "ageTo",
  Distance = "distance",
  Page = "page",
  Size = "size",
}
